// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sofa.Identity.EntityFramework.Context;

namespace Sofa.Identity.EntityFramework.Migrations
{
    [DbContext(typeof(SofaIdentityDbContext))]
    [Migration("20200206061342_is1")]
    partial class is1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sofa.Identity.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName");

                    b.Property<int>("Level");

                    b.Property<DateTime>("ModifyDate");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("Role");

                    b.Property<int>("RowVersion");

                    b.Property<Guid?>("UserCurrentCourseId");

                    b.Property<Guid?>("UserCurrentSyllabusId");

                    b.Property<string>("UserName");

                    b.HasKey("Id")
                        .HasName("PK_IDN_User");

                    b.ToTable("IDN_User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("731874e2-b89c-4509-819a-5b69396a336b"),
                            CreateDate = new DateTime(2020, 2, 6, 9, 43, 42, 504, DateTimeKind.Local).AddTicks(8307),
                            Description = "",
                            Email = "jahanbin.ali1988@gmail.com",
                            FirstName = "Ali",
                            IsActive = true,
                            LastName = "Jahanbin",
                            Level = 0,
                            ModifyDate = new DateTime(2020, 2, 6, 9, 43, 42, 507, DateTimeKind.Local).AddTicks(279),
                            PasswordHash = "JB661pQ8yCirbaGKuNu8wIZjd7/lq74u5bDYUaX6GW0=",
                            PhoneNumber = "09224957626",
                            Role = 0,
                            RowVersion = 0,
                            UserCurrentCourseId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserCurrentSyllabusId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "sysadmin"
                        },
                        new
                        {
                            Id = new Guid("253e472e-21ac-4864-b218-b364169d0611"),
                            CreateDate = new DateTime(2020, 2, 6, 9, 43, 42, 520, DateTimeKind.Local).AddTicks(5951),
                            Description = "",
                            Email = "jahanbinali88@yahoo.com",
                            FirstName = "Ali",
                            IsActive = true,
                            LastName = "Jahanbin",
                            Level = 0,
                            ModifyDate = new DateTime(2020, 2, 6, 9, 43, 42, 520, DateTimeKind.Local).AddTicks(6014),
                            PasswordHash = "JB661pQ8yCirbaGKuNu8wIZjd7/lq74u5bDYUaX6GW0=",
                            PhoneNumber = "09224957626",
                            Role = 1,
                            RowVersion = 0,
                            UserCurrentCourseId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserCurrentSyllabusId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "teacher"
                        },
                        new
                        {
                            Id = new Guid("50ecc8e1-5c5c-4a97-a5f5-af9e9eba1b70"),
                            CreateDate = new DateTime(2020, 2, 6, 9, 43, 42, 530, DateTimeKind.Local).AddTicks(1185),
                            Description = "",
                            Email = "jahanbin.ali1988@yahoo.com",
                            FirstName = "Ali",
                            IsActive = true,
                            LastName = "Jahanbin",
                            Level = 0,
                            ModifyDate = new DateTime(2020, 2, 6, 9, 43, 42, 530, DateTimeKind.Local).AddTicks(1201),
                            PasswordHash = "JB661pQ8yCirbaGKuNu8wIZjd7/lq74u5bDYUaX6GW0=",
                            PhoneNumber = "09224957626",
                            Role = 1,
                            RowVersion = 0,
                            UserCurrentCourseId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserCurrentSyllabusId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserName = "student"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
